### ISSUE TITLE
Product Variation not working 

### ISSUE THREAD

**Issue by Samverylazy** [qTranslate-Team/qtranslate-x#160] opened 2015-05-18 00:24 UTC
Hi, I using WooCommerce & qTranslate-X in my theme, but I found that "Product Data" not changing when I switch language tabs.

Could you have a look at this problem? BTW, I am using WooCommerce & qTranslate-X 1.1 and qTranslate-X 3.3 version, also WooCommerce 2.3.8.

Thanks

**Comment by johnclause** [comment] 2015-05-18 01:29
Duplicate of https://github.com/qTranslate-Team/woocommerce-qtranslate-x/issues/15

**Closed by johnclause** 2015-05-18 01:29 UTC
Labels: duplicate
