### ISSUE TITLE
Menu items display in just one lenguage

### ISSUE THREAD

**Issue by paoPuscher** [qTranslate-Team/qtranslate-x#377] opened 2016-04-16 20:28 UTC
and now all the sub menus are displaying french text when they should be displaying spanish content... please I need help and am willing to pay for your help!

**Comment by paoPuscher** [comment] 2016-04-16 20:29
the site again is Laubadia.com

**Comment by paoPuscher** [comment] 2016-04-16 20:31
Menu titles are in spanish and submenu items in french, and then the content is in spanish!!!

![menuandsubmenus](https://cloud.githubusercontent.com/assets/18504269/14583460/e27dc008-0422-11e6-88b6-53e9d27d1cff.jpg)

**Comment by collaer** [comment] 2016-04-18 05:55
i suppose it's the same as #374, you case use their workaround

**Comment by paoPuscher** [comment] 2016-04-18 11:53
It is... thankyou @collaer  ...   I am working around the issue...   hope it doesn't break with a new Wordpress version... do you know why my portfolio crumbtrails are displaying as if the qTranslate plugin wasn't enabled? when it is enabled?
![crumbtrails](https://cloud.githubusercontent.com/assets/18504269/14603245/eeda7ee0-056c-11e6-80ca-d8dea12d34e5.jpg)

**Comment by johnclause** [comment] 2016-04-20 01:12
Duplicate of  #374, Also read https://wordpress.org/support/topic/issues-with-wordpress-45 for the status.

**Closed by johnclause** 2016-04-20 01:12 UTC
Labels: duplicate
