### ISSUE TITLE
Crashes Firefox with Adblock Plus extension

### ISSUE THREAD

**Issue by CKtalon** [qTranslate-Team/qtranslate-x#93] opened 2015-03-21 23:25 UTC
With Qtranslate-X 3.2.9, a user with adblock pro plugin with Firefox will experience a crash. Disabling the plugin or adblock plus prevents the crash. It began since 3.2.9. Works fine in 3.2.7

**Comment by mweimerskirch** [comment] 2015-03-22 15:48
Browser plugins are not supposed to crash because of code on a page. You should report this to the AdBlock developers.

**Comment by johnclause** [comment] 2015-03-23 02:55
Give us a link to plugin in trouble, otherwise we cannot reproduce it, while Michel (@mweimerskirch) is correct, it is a good idea to take the issue with them too.

You may also try your luck with the latest version of qTranslate-X from <a href="https://github.com/qTranslate-Team/qtranslate-x">GitHub</a>, which you can download with 'Download ZIP' button on GitHub page or press <a href="https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip">here</a> for the sake of convenience. It has some modifications on URL convert and redirections, which might affect this issue.

**Comment by CKtalon** [comment] 2015-03-23 03:02
The plugin is Firefox's Adblock Plus 2.6.8 (sorry for calling it pro earlier): https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/

**Comment by johnclause** [comment] 2015-03-23 03:08
I installed it and nothing is crashing for me. Does it still crash on you with the latest version from GitHub?

**Comment by CKtalon** [comment] 2015-03-23 03:20
With the latest version 3.2.9.1, it still crashes. Had to revert back to 3.2.7 to not have it crash. I'm also getting various reports from users. Some crash while some don't.

**Comment by johnclause** [comment] 2015-03-23 04:56
Ok, then it indeed should be taken to them. How does it crash? All pages? An first load? click on something? Which url crashes? Does it have anything to do with redirections? They are going to ask all those questions too. You need to figure out a reproducible case, which anyone can repeat, then report it to them and they may fix it. Why Firefox? Who a hell now using Firefox ;) It is in the past ... ;)

**Comment by CKtalon** [comment] 2015-03-23 04:59
It crashes on load of the page. It happens both on OSX and Windows.

I decided it was likely qTranslate-X since a change between 3.2.9 and 3.2.7 broke something that interfered with the popular ABP extension. I will do more testing among my users to get more information. Thank you.

**Comment by spartacus-zeus** [comment] 2015-04-02 18:35
Cannot reproduce with current Github master. Which lists are you using?

**Comment by johnclause** [comment] 2015-05-17 22:26
I assume it is resolved issue now? I am closing it for now, we can still write to closed issue and we can re-open it if needed.

**Closed by johnclause** 2015-05-17 22:26 UTC
Labels: question
