### ISSUE TITLE
Adding permlink incorrecly in WP backend

### ISSUE THREAD

**Issue by Lesrad** [qTranslate-Team/qtranslate-x#166] opened 2015-05-28 12:45 UTC
Hi John,
Thought I would just let you know of a minor bug, that doesn't have any real implication.

With the following options selected:
- Use Pre-Path Mode (Default, puts /en/ in front of URL). SEO friendly.
- Hide URL language information for default language.

The permalink displays incorrectly in the editor backend.

i.e the permalink path includes the default language when it should not.

see: https://wordpress.org/support/topic/plugin-adding-en-to-new-posts-and-edit-posts?replies=5

**Comment by johnclause** [comment] 2015-05-31 02:16
Well, in fact, this is by design, since this is supposed to be a link to **switch** the language, not to **keep** current one: https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/

I am closing this issue for now to save clicks, we can still write to closed issue and can re-open it if necessary.

**Closed by johnclause** 2015-05-31 02:16 UTC
Labels: question
