### ISSUE TITLE
Doesn't work at all!!

### ISSUE THREAD

**Issue by chiflon** [qTranslate-Team/qtranslate-x#370] opened 2016-04-01 09:29 UTC
Can't switch between langs in all websites with qtranslate
When I'm in /en and I want to go to / it redirects again to /en

Please solve it!!

**Comment by johnclause** [comment] 2016-04-02 03:29
This is by design, it was well discussed here https://qtranslatexteam.wordpress.com/browser-redirection-based-on-language/ This page is linked from many places.

I am closing this now, we can still write into closed issue or we can reopen it, if needed.

**Closed by johnclause** 2016-04-02 03:29 UTC

**Comment by johnclause** [comment] 2016-04-02 03:32
Duplicate of https://github.com/qTranslate-Team/qtranslate-x/issues/33
