### ISSUE TITLE
qTranslate problem with widget

### ISSUE THREAD

**Issue by evilmc** [qTranslate-Team/qtranslate-x#241] opened 2015-09-02 16:06 UTC
I am add some information on my website, but i dont know why, everytime i add something in serbian for example and i save it, it saves the content in english language and does not allow me save in serbian...

U use latest wp, and qtx

thanx

**Comment by johnclause** [comment] 2015-09-02 18:30
Need steps to reproduce.

**Comment by evilmc** [comment] 2015-09-02 20:16
I don't understand, what you mean?

**Comment by Grafcom** [comment] 2015-09-03 07:00
@evilmc 
what theme and what plugins you use? What are the settings for qTranslate X?

**Comment by jimbocook** [comment] 2015-09-03 22:12
How big is your menu. The standard WordPress admin for menus can't handle very long menus (it runs up against the default php max_input_vars limit (1000) and adding translations can make the issue appear fairly quickly. If that's the issue raising the limit to 2000 (or more) might resolve it.

**Comment by evilmc** [comment] 2015-09-07 01:23
I use latest WP and latest qTx and again I have problem with widgets...Can't save in other language, always save one.

**Comment by evilmc** [comment] 2015-09-10 18:14
Any fix for my problem?

**Comment by Grafcom** [comment] 2015-09-10 19:50
@evilmc 
you'll have to explain your problem more specific.... Give an example in detail - step for step

**Comment by johnclause** [comment] 2015-09-12 18:40
In order to solve a problem we need to be able to reproduce it on our servers, which is currently not possible because we

- do not have steps how to reproduce (your description is too short to understand)
- do not have that premium theme.

Do you have the same problem under one of the standard theme provided by Wordpress for free? Can you setup an example of your problem under such a standard theme with the minimum number of active plugins? Give us step-by-step instructions how to reproduce your problem.

If it is related to the theme, then probably try to contact the theme developers. Show them how it works fine under standard theme.

This document may also help: https://qtranslatexteam.wordpress.com/troubleshooting/

**Comment by johnclause** [comment] 2015-09-15 04:22
I assume the problem went away - closing the issue, we may still write into closed issue or can reopen it if needed.

**Closed by johnclause** 2015-09-15 04:22 UTC
Labels: question
