### ISSUE TITLE
Tags not shown correctly in frontend

### ISSUE THREAD

**Issue by wocmultimedia** [qTranslate-Team/qtranslate-x#184] opened 2015-06-22 15:37 UTC
Hi John,

I have a little issue you can see at http://www.wocmultimedia.biz/it/tag/travelblog/   . If you hover this menu the Item translation is messed up. You can see English and Italian word in the same menu that is supposed to be in Italian only. 
2- I also had another strange behaviour, tags are not changeable in a duplicated post. 
Today, I duplicated a post to keep some formatting and tags but there was no way to change the tags. I deleted two or three not needed and after saving old tags were set again on place. I had to delete all present tags in the post then re-add all tags again.
I don't know if it is also a theme issue but till last week I worked without problem.
Please, have a check.
Thanks
Angelo

**Comment by johnclause** [comment] 2015-06-23 02:51
1. I do not see anything wrong. Please, give me specific example where to look at. Are those items entered to be multilingual at admin side? How do you see them in menu editor, also incorrect? Do you see English and Italian for the same menu item, or some items in English and some in Italian?

2. Cannot reproduce. Please, give me the steps.

**Comment by wocmultimedia** [comment] 2015-06-23 08:12
Hi,

1- test this link http://www.wocmultimedia.biz/it/  and _hover_ on *Blog 
& Viaggi* menu. You will see that there are some items in English and 
some Italian.
i.e. FINNISH LAPLAND (must be in Italian LAPPONIA FINLANDESE) , ITALY 
(ITALIA)  while you see correctly shown DANIMARCA
If I look at tags in admin panel all items are correctly translated in 
both languages.
I tried to deactivate and reactivate the plugin without any success. I 
also tried to edit a single wrong shown item like we did at beginning 
when migrated from mqtranslate but no changes.

2- I duplicated a post as usual. I edited the post and then I deleted 
some tags but on saving older tags replaced my modifications. In this 
case I add to delete all old items, save and re-insert the needed tags.

If you need admin data to enter write me in private and I give access data.
Thanks
Angelo


Il 23/06/2015 04:51, johnclause ha scritto:
>
> 1.
>
>     I do not see anything wrong. Please, give me specific example
>     where to look at. Are those items entered to be multilingual at
>     admin side? How do you see them in menu editor, also incorrect? Do
>     you see English and Italian for the same menu item, or some items
>     in English and some in Italian?
>
> 2.
>
>     Cannot reproduce. Please, give me the steps.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-114334966>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-23 14:36
1. What about menu editor, /wp-admin/nav-menus.php? I suppose you may fix whatever is wrong in menu editor, although I do not understand how that happened at first place. What is entered in menu editor is where menu gets information from when is being rendered, not from the original tag.

2. "I duplicated a post as usual" - how do you do it usually?

**Comment by wocmultimedia** [comment] 2015-06-23 17:15
Well John,

1- The problem is in the plugin indeed. I cannot edit all times what is 
wrong. Other menus are correct so why this of tags not?
I wish you can fix it.
Thanks
Angelo

Il 23/06/2015 16:36, johnclause ha scritto:
>
> 1.
>
>     What about menu editor, /wp-admin/nav-menus.php? I suppose you may
>     fix whatever is wrong in menu editor, although I do not understand
>     how that happened at first place. What is entered in menu editor
>     is where menu gets information from when is being rendered, not
>     from the original tag.
>
> 2.
>
>     "I duplicated a post as usual" - how do you do it usually?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-114527775>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-23 23:58
Hi Angelo, I still do not know how to reproduce neither #1 nor #2. What do you mean it "worked" correctly? What has changed since it worked?

"If you remember we had Tag problems" - that was not menu related and it was about tags for products attributes. Are these tags you talk about also for product attributes?

And I still do not know where is the button which you press to duplicate a post. I do not see it anywhere on my testing server. I need precise step-instructions for all you are talking about. Yes, send me access data, if you can, but I would still need instructions what exactly to look at.

**Comment by wocmultimedia** [comment] 2015-06-24 07:30
Hi John.

This email is not private to send admin data. Let me know a safe way to 
send you admin data.

I will also send how to reproduce in my site the problem

Thanks
Angelo

Il 24/06/2015 01:58, johnclause ha scritto:
>
> Hi Angelo, I still do not know how to reproduce neither #1 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/1> nor #2 
> <https://github.com/qTranslate-Team/qtranslate-x/pull/2>. What do you 
> mean it "worked" correctly? What has changed since it worked?
>
> "If you remember we had Tag problems" - that was not menu related and 
> it was about tags for products attributes. Are these tags you talk 
> about also for product attributes?
>
> And I still do not know where is the button which you press to 
> duplicate a post. I do not see it anywhere on my testing server. I 
> need precise step-instructions for all you are talking about. Yes, 
> send me access data, if you can, but I would still need instructions 
> what exactly to look at.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-114677581>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by wocmultimedia** [comment] 2015-06-24 13:24
I made another test.

I deactivated all plugins including qTranslateX, switched to 2015 theme and assigning the menu to primary menu I found that also the Danimarca (Denmark) item correctly shown when the plugin is activated results without translation. The only one including language quicktags is Finlandia (Suomi-Finland). All other items seems don’t have translation.
If I go to Appearance > Menus and items are all correctly translated the same if I go to Posts> Tags.
Also creating a new tag is shown only in english.
Is only post tag not other kind of translation.

Angelo

**Comment by wocmultimedia** [comment] 2015-06-24 14:04
Hi John,

I reinstalled wp 4.2.2 just in case but no changes happened. Then, I went again in the menus editor and look for the tags not translated. I made a search in the tag window then re-set in the menu.
I found out what can cause the messing. If you have the backend language set to English and changing the menu button language try to edit the Italian menu, the tag content goes in conflict.
In fact, having backend language in English and Menu list in Italian the tag items in the menu appeared to be in English.
I suggest you check the language switching coding at least for the tags in the menu editor.

Now, the menu is correctly showing all items because I re-add all the items
Please, hover  Blog & Viaggi at http://www.wocmultimedia.biz/it/

Thanks
Angelo

**Comment by johnclause** [comment] 2015-06-24 17:01
Hi Angelo, what you describe sounds crazy unbelievable ;) Which version of qTranslate-X do you play with? We will need to apply fixes to the latest from [GitHub](https://github.com/qTranslate-Team/qtranslate-x) in any case. It has a lot of changes. Could you try that before we are engaged with the fixes?

**Comment by wocmultimedia** [comment] 2015-06-24 18:05
Hi,
I sent you a private email with access data

Angelo

Il 24/06/2015 19:01, johnclause ha scritto:
>
> Hi Angelo, what you describe sounds crazy unbelievable ;) Which 
> version of qTranslate-X do you play with? We will need to apply fixes 
> to the latest from GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x> in any case. It has 
> a lot of changes. Could you try that before we are engaged with the fixes?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-114942274>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-25 04:34
Thanks for the access, Angelo. I went to menu editor http://www.wocmultimedia.biz/wp-admin/nav-menus.php?action=edit&menu=28 and I found out that some menu entries are translated, while others are not. For example, "Italia" under "Blogg & Viaggi" was not translated. I entered translation for English and it started appearing correctly in menu. To easily see which one is translated and which one is not, I set option "Editor Mode" to value "Editor Raw Mode". You can see that there are like 20-30 menu items that are not multilingual.

I believe that fixing them manually will make it work correctly.

However, I have no idea how that got messed up at first place. When I try to add a new menu item of type "Tag" I see that in the list of all tags on left side under accordion "Tags", many tags are not translated. It is easy to spot them in "Editor Raw Mode". So I do not really know. All works as designed, just some items do not have multilingual values.

Maybe, this is what happened. When you first added an item to menu it did not have multilingual value. Then you entered multilingual value in tag itself, but that does not automatically update menu entries and they stayed as they were in the beginning. Does this match what you can remember?

**Comment by wocmultimedia** [comment] 2015-06-25 07:30
Hi John,

I saw the same problem but the tags if you go to Posts >  Tags are all 
translated and I created all tags with both languages at once. I also 
created some tags from inside a new post then I went to Tags section and 
add translation. They works correctly. In fact, if you  check this link 
you will see that the same item *POLONIA* (wrong in the English Menu and 
appearing not translated)  it's translated and appears correctly how 
*Poland* in the post http://www.wocmultimedia.biz/en/tag/poland/

The _problem is in the menu editor not elsewhere_ and changing manually 
the items doesn't work because then when reopen the menu it's changed 
again. Yesterday I changed all items, refreshing that menu one by one 
and you see now is the English version being messed.

I suggest to investigate in how the menu editor grab the tags

Thanks
Angelo

Il 25/06/2015 06:34, johnclause ha scritto:
>
> Thanks for the access, Angelo. I went to menu editor 
> http://www.wocmultimedia.biz/wp-admin/nav-menus.php?action=edit&menu=28 and 
> I found out that some menu entries are translated, while others are 
> not. For example, "Italia" under "Blogg & Viaggi" was not translated. 
> I entered translation for English and it started appearing correctly 
> in menu. To easily see which one is translated and which one is not, I 
> set option "Editor Mode" to value "Editor Raw Mode". You can see that 
> there are like 20-30 menu items that are not multilingual.
>
> I believe that fixing them manually will make it work correctly.
>
> However, I have no idea how that got messed up at first place. When I 
> try to add a new menu item of type "Tag" I see that in the list of all 
> tags on left side under accordion "Tags", many tags are not 
> translated. It is easy to spot them in "Editor Raw Mode". So I do not 
> really know. All works as designed, just some items do not have 
> multilingual values.
>
> Maybe, this is what happened. When you first added an item to menu it 
> did not have multilingual value. Then you entered multilingual value 
> in tag itself, but that does not automatically update menu entries and 
> they stayed as they were in the beginning. Does this match what you 
> can remember?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115102483>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by wocmultimedia** [comment] 2015-06-25 15:44
Hello John,

What happen? Have you made some changes? Because now Posts have no 
switcher in the backend, it's all messed!

Please, check it
Thanks
Angelo

Il 25/06/2015 06:34, johnclause ha scritto:
>
> Thanks for the access, Angelo. I went to menu editor 
> http://www.wocmultimedia.biz/wp-admin/nav-menus.php?action=edit&menu=28 and 
> I found out that some menu entries are translated, while others are 
> not. For example, "Italia" under "Blogg & Viaggi" was not translated. 
> I entered translation for English and it started appearing correctly 
> in menu. To easily see which one is translated and which one is not, I 
> set option "Editor Mode" to value "Editor Raw Mode". You can see that 
> there are like 20-30 menu items that are not multilingual.
>
> I believe that fixing them manually will make it work correctly.
>
> However, I have no idea how that got messed up at first place. When I 
> try to add a new menu item of type "Tag" I see that in the list of all 
> tags on left side under accordion "Tags", many tags are not 
> translated. It is easy to spot them in "Editor Raw Mode". So I do not 
> really know. All works as designed, just some items do not have 
> multilingual values.
>
> Maybe, this is what happened. When you first added an item to menu it 
> did not have multilingual value. Then you entered multilingual value 
> in tag itself, but that does not automatically update menu entries and 
> they stayed as they were in the beginning. Does this match what you 
> can remember?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115102483>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by qtranslateteam** [comment] 2015-06-25 15:46
Angelo, don't you read my messages ;) I set "Raw Editor Mode" Please, read
everything attentively.

On Thu, Jun 25, 2015 at 8:44 AM, wocmultimedia <notifications@github.com>
wrote:

> Hello John,
>
> What happen? Have you made some changes? Because now Posts have no
> switcher in the backend, it's all messed!
>
> Please, check it
>
> Thanks
> Angelo
>
> Il 25/06/2015 06:34, johnclause ha scritto:
> >
> > Thanks for the access, Angelo. I went to menu editor
> > http://www.wocmultimedia.biz/wp-admin/nav-menus.php?action=edit&menu=28
> and
> > I found out that some menu entries are translated, while others are
> > not. For example, "Italia" under "Blogg & Viaggi" was not translated.
> > I entered translation for English and it started appearing correctly
> > in menu. To easily see which one is translated and which one is not, I
> > set option "Editor Mode" to value "Editor Raw Mode". You can see that
> > there are like 20-30 menu items that are not multilingual.
> >
> > I believe that fixing them manually will make it work correctly.
> >
> > However, I have no idea how that got messed up at first place. When I
> > try to add a new menu item of type "Tag" I see that in the list of all
> > tags on left side under accordion "Tags", many tags are not
> > translated. It is easy to spot them in "Editor Raw Mode". So I do not
> > really know. All works as designed, just some items do not have
> > multilingual values.
> >
> > Maybe, this is what happened. When you first added an item to menu it
> > did not have multilingual value. Then you entered multilingual value
> > in tag itself, but that does not automatically update menu entries and
> > they stayed as they were in the beginning. Does this match what you
> > can remember?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115102483
> >.
> >
>
>
>
> ---
> Questa e-mail è stata controllata per individuare virus con Avast
> antivirus.
> https://www.avast.com/antivirus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115299234>
> .
>



-- 
John Clause
qTranslate Team
https://qtranslatexteam.wordpress.com/about/

**Comment by johnclause** [comment] 2015-06-25 15:54
Hi Angelo, it seems I am not explaining it well. I cannot reproduce the problem. I reload menu and my changes are there, nothing disappeared. Perhaps you do not realize that menu editor allows you to change the entry on menu, which does not have to match the tag title on tag itself?

* Click little triangle on the right to open editor and you will see a number of fields to modify including "Title".
* Enter multilingual value in field "Title".
* Press blue button "Save Menu".

Now your menu entry is multilingual and is shown correctly.

Once again, when you edit "Title" of menu entry, it is not the same as editing title of Tag for tag itself.

When add tag menu item for the first time, it gets stored in database with empty field "Title". When it is displayed, wp check the title entry for menu and if it is empty the title of original item is fetched and is used. However, once menu title field is not empty, the original item is never checked again and menu entry title is always used.

You need to enter multilingual values in title fields in menu editor.

Does this help?

**Comment by wocmultimedia** [comment] 2015-06-25 15:57
Hi John,

Ok, sorry but I didn't know what Raw Editor was. Then I went to Settings 
 > Languages and look for the part about the LSB button so I found it.
Well, have you found the solution to the Menu issue? Because I set 
properly the tag values at beginning and they are in fact correctly 
shown in the post when you switch in frontend.
I will edit one item in the menu again but yesterday I did it and at 
beginning worked correctly then again messed but in the English version.
This time I try to use the single language mode editor and see what 
happen or are you working on a fixing?

Thanks for your precious support!!!
Angelo

Il 25/06/2015 17:46, qtranslateteam ha scritto:
> Angelo, don't you read my messages ;) I set "Raw Editor Mode" Please, read
> everything attentively.
>
> On Thu, Jun 25, 2015 at 8:44 AM, wocmultimedia <notifications@github.com>
> wrote:
>
> > Hello John,
> >
> > What happen? Have you made some changes? Because now Posts have no
> > switcher in the backend, it's all messed!
> >
> > Please, check it
> >
> > Thanks
> > Angelo
> >
> > Il 25/06/2015 06:34, johnclause ha scritto:
> > >
> > > Thanks for the access, Angelo. I went to menu editor
> > > 
> http://www.wocmultimedia.biz/wp-admin/nav-menus.php?action=edit&menu=28
> > and
> > > I found out that some menu entries are translated, while others are
> > > not. For example, "Italia" under "Blogg & Viaggi" was not translated.
> > > I entered translation for English and it started appearing correctly
> > > in menu. To easily see which one is translated and which one is not, I
> > > set option "Editor Mode" to value "Editor Raw Mode". You can see that
> > > there are like 20-30 menu items that are not multilingual.
> > >
> > > I believe that fixing them manually will make it work correctly.
> > >
> > > However, I have no idea how that got messed up at first place. When I
> > > try to add a new menu item of type "Tag" I see that in the list of all
> > > tags on left side under accordion "Tags", many tags are not
> > > translated. It is easy to spot them in "Editor Raw Mode". So I do not
> > > really know. All works as designed, just some items do not have
> > > multilingual values.
> > >
> > > Maybe, this is what happened. When you first added an item to menu it
> > > did not have multilingual value. Then you entered multilingual value
> > > in tag itself, but that does not automatically update menu entries and
> > > they stayed as they were in the beginning. Does this match what you
> > > can remember?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115102483
> > >.
> > >
> >
> >
> >
> > ---
> > Questa e-mail è stata controllata per individuare virus con Avast
> > antivirus.
> > https://www.avast.com/antivirus
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115299234>
> > .
> >
>
>
>
> -- 
> John Clause
> qTranslate Team
> https://qtranslatexteam.wordpress.com/about/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115299665>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-25 16:00
Angelo, I did not observe a problem to be fixed yet. All I did worked as expected.

**Comment by wocmultimedia** [comment] 2015-06-25 16:04
Hi John,

Now I understood and you explained in plain word for me. I didn't know 
the mechanism used by WP but I guessed some months ago that something 
unusual was in WP.
Is this only related to Tags in  the  Menu?
Can you tell me which Item you modified so I can understand completely 
this mechanism?

Your support is precious and I can help others and solve it in my other 
sites too.

Thanks again
Angelo


Il 25/06/2015 17:54, johnclause ha scritto:
>
> Hi Angelo, it seems I am not explaining it well. I cannot reproduce 
> the problem. I reload menu and my changes are there, nothing 
> disappeared. Perhaps you do not realize that menu editor allows you to 
> change the entry on menu, which does not have to match the tag title 
> on tag itself?
>
>   * Click little triangle on the right to open editor and you will see
>     a number of fields to modify including "Title".
>   * Enter multilingual value in field "Title".
>   * Press blue button "Save Menu".
>
> Now your menu entry is multilingual and is shown correctly.
>
> Once again, when you edit "Title" of menu entry, it is not the same as 
> editing title of Tag for tag itself.
>
> When add tag menu item for the first time, it gets stored in database 
> with empty field "Title". When it is displayed, wp check the title 
> entry for menu and if it is empty the title of original item is 
> fetched and is used. However, once menu title field is not empty, the 
> original item is never checked again and menu entry title is always used.
>
> You need to enter multilingual values in title fields in menu editor.
>
> Does this help?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115302378>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-25 16:15
Hi Angelo, what I modified I reported in my messages. Yes, somehow it got messed up at first place, and that I do not understand, but now it is easy to fix. Yes, same is applicable to all menu items, not only tags. Please, do not forget to close the issue when you are done and all is good, use "Close and comment" button.

**Comment by wocmultimedia** [comment] 2015-06-25 17:56
Hi John,

I will investigate all items and re-translate them but they were working 
correctly before. I suppose the problem happened with latest WP update 
from 4.2 to 4.2.2 any items were in perfect order and your plugin worked 
fine.
If an issue exists is in the compatibility with latest core modification 
not elsewhere. Is not the first time that a fixing for bugs creates 
worst issues this is why I use a plugin to prevent automatic WP updates.

I will close the issue after I get the result.

Thanks a lot.
Angelo

Il 25/06/2015 18:15, johnclause ha scritto:
>
> Hi Angelo, what I modified I reported in my messages. Yes, somehow it 
> got messed up at first place, and that I do not understand, but now it 
> is easy to fix. Yes, same is applicable to all menu items, not only 
> tags. Please, do not forget to close the issue when you are done and 
> all is good, use "Close and comment" button.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115307343>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-25 18:19
Hi Angelo, the site you gave me access to, is it live or test-copy? Do you have a [test-copy](https://qtranslatexteam.wordpress.com/how-to-site-test-copy/)? You should try any updates on a test-copy first before doing it on the live site. I hope this is how you are doing it?

I am thinking to take an opportunity and to test the latest version of qtx on your site before releasing it, since you seem to have a complex enough setup and if all is good on your site, it would make me feel more comfortable to release it to everybody. What do you think?

**Comment by wocmultimedia** [comment] 2015-06-25 18:34
Hi John,

This is my final report before closing the issue. Please, take care of 
my notes.

1-I switched to single language to better see the problem
2- As you stated there were about 30 items not translated that 
previously they were translated. It doesn't matter so I proceeded in 
this way.
3- I opened Categories in another tab and checked the untraslated in the 
menu. I made the translation, saved and also refreshed the menu tab. The 
categories updated resulted also automatically updated in the menu list.
4- I found some Product Category, I did the same process opening Product 
Categories in another tab, re-translated, saved and refreshed the menu 
tab too. Also, in this case Product Categories were automatically 
updated in the menu list.
5- I repeated the same process with the Tags but *here's the problem.* 
The tag appeared translated in tag section/page. I tried to retranslate, 
saved and refreshing the menu tab they were not automatically updated. 
So I had to update manually, using the little triangle to open the menu 
item title and change locally the translations.

Hence, the menu issue is related only with Tags that do not update 
automatically when you makes changes in their Tags section/page. If this 
is a normal Wp behaviour, it is really an unprofessional behaviour that 
surprise me. It's inconceivable because if you write a Post and add a 
tag, it is not inserted in double or more languages but you can just add 
it in one language. Then you go in Post > Tags and make the due 
translations. In two single language sites I'm maintaining this never 
happened. _So maybe_ some incompatibilities exist between qTranslateX 
and the wp core. If nobody reported it before, maybe is because they 
don't use Tags in menu or combined with woocommerce.

I hearty wish my feedback could be useful to you.
Thanks a lot!!!

Angelo

Il 25/06/2015 18:15, johnclause ha scritto:
>
> Hi Angelo, what I modified I reported in my messages. Yes, somehow it 
> got messed up at first place, and that I do not understand, but now it 
> is easy to fix. Yes, same is applicable to all menu items, not only 
> tags. Please, do not forget to close the issue when you are done and 
> all is good, use "Close and comment" button.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115307343>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by wocmultimedia** [comment] 2015-06-25 18:36
Hi John,

Is a live site! I don't have a test-copy sorry.

I prefer better don't test with my site that I just corrected and now 
seems working

Thanks
Angelo


Il 25/06/2015 20:19, johnclause ha scritto:
>
> Hi Angelo, the site you gave me access to, is it live or test-copy? Do 
> you have a test-copy 
> <https://qtranslatexteam.wordpress.com/how-to-site-test-copy/>? You 
> should try any updates on a test-copy first before doing it on the 
> live site. I hope this is how you are doing it?
>
> I am thinking to take an opportunity and to test the latest version of 
> qtx on your site before releasing it, since you seem to have a complex 
> enough setup and if all is good on your site, it would make me feel 
> more comfortable to release it to everybody. What do you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115352756>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by johnclause** [comment] 2015-06-25 18:59
Well, Angelo, having a test-copy is a really good idea and most of professional admins always test any change on a test copy first, before applying the same actions to live site. For the sake of being able to test, I am willing to help you to make a test copy, which you will keep using later for all future updates. Plugin Duplicator makes duplication very easy. You only need to create a subdomain like test.wocmultimedia.biz or similar of a choice pointed in a separate folder using admin panel of your provider. Close the access to it with a password in order not to confuse SEO. The actual copy may be done with Duplicator. If you give me access to your provider control panel I could do the whole thing for you. It is not as scary as it seems to be, but the benefits are hard to underestimate.

**Comment by wocmultimedia** [comment] 2015-06-25 19:36
How long do you need to use my provider control panel?

Let me know so I will send to your email the data and when you finish I 
change my access data password



Il 25/06/2015 20:59, johnclause ha scritto:
>
> Well, Angelo, having a test-copy is a really good idea and most of 
> professional admins always test any change on a test copy first, 
> before applying the same actions to live site. For the sake of being 
> able to test, I am willing to help you to make a test copy, which you 
> will keep using later for all future updates. Plugin Duplicator makes 
> duplication very easy. You only need to create a subdomain like 
> test.wocmultimedia.biz or similar of a choice pointed in a separate 
> folder using admin panel of your provider. Close the access to it with 
> a password in order not to confuse SEO. The actual copy may be done 
> with Duplicator. If you give me access to your provider control panel 
> I could do the whole thing for you. It is not as scary as it seems to 
> be, but the benefits are hard to underestimate.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qTranslate-Team/qtranslate-x/issues/184#issuecomment-115362486>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Closed** 2015-10-14 06:28 UTC
Labels: question
