### ISSUE TITLE
Cannot switch back to default language in front end

### ISSUE THREAD

**Issue by SteFunZH** [qTranslate-Team/qtranslate-x#189] opened 2015-06-29 19:23 UTC
My default language is DE and I have EN as a second language.
I just discovered that I cannot switch back from second to default language anymore unless I delete the cookie. I constantly get redirected to /en… even if I put in a /de URL manually.
What am I missing?
Using WP 4.2.2 and qtranslate-x 3.3

**Comment by johnclause** [comment] 2015-06-29 19:35
I have no way to reproduce it. Try following https://qtranslatexteam.wordpress.com/troubleshooting/ ?

**Comment by SteFunZH** [comment] 2015-06-29 19:50
it happens on my site here: http://www.formelfun.ch/
It might redirect you to /en because of your browser language. If that happens to me, I cannot switch back to default (DE), neither with Safari nor Firefox. The language switch is on the top left of the page.

**Comment by johnclause** [comment] 2015-06-29 20:01
I still have no idea. .htaccess is messed up? Any error messages in error_log? Does "Debug Bar" show any errors?

**Comment by johnclause** [comment] 2015-06-29 20:04
I see a number of errors in Java console, which may  be unrelated, but  try to resolve them first.

**Comment by SteFunZH** [comment] 2015-06-29 20:08
Thank you, John! I will dig a bit further now.

**Comment by bmachuel** [comment] 2015-09-18 13:52
Might be a cookie or cache issue. I have the same problem but only with Chrome. When I switch to an other browser everything is back to normal.

Have you found out what the problem was?

**Comment by bmachuel** [comment] 2015-09-18 14:04
Definitely a cookie issue. There were quite a lot of occurrences of the qtrans_front_language cookie. Deleting all of them solved the problem.

Isn't it something that should be solved in a future release?

**Comment by SteFunZH** [comment] 2015-09-18 14:22
I always thought it was around cookies, but behaviour was strange to me.
I came that far, that I switched to Query Mode (?lang=en)
Since WP 4.3.1 I switched back to pre path mode and it seems to work again, however.

Deleting the cookie before only helped once, until the next language switch, then it got stuck again.

**Comment by johnclause** [comment] 2015-09-20 19:29
Could you try the latest version from [GitHub](https://github.com/qTranslate-Team/qtranslate-x)? Nothing was done specifically to this problem, but there are some changes. Does this problem stay?

**Comment by bmachuel** [comment] 2015-09-26 13:01
Yes, the problem stays after installing the GitHub latest version.
-------


johnclause a écrit:

**Comment by bmachuel** [comment] 2015-09-26 16:24
BTW, the latest version of QTX available on GitHub seems to insert 
unwanted paragraph tags at the top of pages.
Best wishes,
Benoît Machuel
-------


johnclause a écrit :

**Comment by johnclause** [comment] 2015-09-27 01:04
I need step-by-step instructions to reproduce, since I cannot see that, and nothing really was changed with that regard. Please, open a new issue with the steps, since it does not fit in this topic. Thanks a lot.

**Comment by johnclause** [comment] 2015-09-27 02:00
>Yes, the problem stays after installing the GitHub latest version

Since there is no way to reproduce, the only way left is to make a test-copy and to give us access to your server: https://qtranslatexteam.wordpress.com/admin-access/

**Comment by bmachuel** [comment] 2015-10-07 10:33
I suppose we are still talking about the cookie issue.
You can easily check on our website directly: 
http://www.fim-musicians.org. After a couple of language switches, you 
cannot get back to default language unless the qtrans_front_language 
cookie is removed (likely to be present in more than one occurrence - 
there were about 15 last time I checked).
-------

johnclause a écrit :

**Comment by Grafcom** [comment] 2015-10-07 10:43
@ bmachuel
I have <b>a lot of times</b> changed languages and could not reproduce what you say. 
Every time I could go back to the default language and so on....

**Comment by johnclause** [comment] 2015-10-07 16:23
@bmachuel, your "problem" is most likely by design and is explained here: https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/.
I cannot see anything wrong with your site.

>BTW, the latest version of QTX available on GitHub seems to insert
unwanted paragraph tags at the top of pages.

@bmachuel: Did you submit step-by-step instructions to reproduce this problem in a new issue, since it does not fit the topic of this issue? As I mentioned, we cannot reproduce it and we need step-instructions to reproduce. I do not recall seeing it yet. If you already submitted, please cite a link to it here.

Oppositely, @SteFunZH has a different problem, easily reproducible, and it is definitely not cookie problem. It is most likely the theme doing things in a very creative and highly unusual way, or server configuration is messed up. One cannot troubleshoot it without seeing logs, browsing file system, making debugging output and so on. You may [contact us](https://qtranslatexteam.wordpress.com/contact-us/) with a request for paid job to [troubleshoot](https://qtranslatexteam.wordpress.com/troubleshooting/) and to [integrate](https://qtranslatexteam.wordpress.com/integration/) qTranslate-X with your theme.

I am closing this issue for now, as there is nothing further we can do here this way. We can still write into a closed issue, or we can re-open it, if needed.

**Closed by johnclause** 2015-10-07 16:23 UTC
Labels: question
