### ISSUE TITLE
Javascript crashes if textarea contains []

### ISSUE THREAD

**Issue by pimteam** [qTranslate-Team/qtranslate-x#387] opened 2016-05-27 12:26 UTC
We have integrated qTranslate X into a plugin that has textareas with names containing "[]" (example: "answer[]") and the Javascript of qTranslate crashes on these pages. Using [] in html input field name is valid and required by PHP to deliver the elements as PHP array on submit. 

This problem did not exist in previous qTranslate X versions.

**Comment by johnclause** [comment] 2016-05-27 14:52
>previous qTranslate X versions

How previous? Can you specify the version? Also the current version you use?

In theory, '[]' should be compatible and it was tested so. I am not sure what is the cause. What is the error message in Java Console (Ctrl+Shift+J)?

**Comment by pimteam** [comment] 2016-05-27 16:34
The version I had before and worked was 3.4.6.4

I can't get an error from the JS console, however the script causes one of those "a script on this page is not responding ... Continue / Stop Script" messages in Firefox.

Looks like the problem is not in the name however. If I remove the name entirely, no problem. If I put ANY name it causes the same problem. And this is not only on my PC. 

Here's the textarea, there are several such ones on the page: 

<textarea name="answer[]" class="i18n-multilingual" rows="3" cols="50" ></textarea>

There are 4 such textareas on the page. I really don't get it what could be wrong.

**Comment by johnclause** [comment] 2016-05-27 16:58
Are you the author of plugin or theme at rouble? Make sure all input fields have unique attribute "id". Is that a case? Do you use JS script, ,json file, or class names to integrate?

**Comment by johnclause** [comment] 2016-05-29 00:52
I guess. this is now resolved with unique "id"s and I am closing this issue. We can still write into closed issue or can reopen it if needed.

**Closed by johnclause** 2016-05-29 00:52 UTC
Labels: question

**Comment by pimteam** [comment] 2016-06-01 09:24
Confirmed, the problem gets resolved by adding unique IDs. Thanks.
