### ISSUE TITLE
Deprecated feature PHP7 error

### ISSUE THREAD

**Issue by growdigital** [qTranslate-Team/qtranslate-x#371] opened 2016-04-02 16:19 UTC
I'd like to use qtranslate-x but I'm getting this error when activating the plugin:
> methods with the same name as their class will not be constructors in a future version of PHP qtranslate

I'm using the [Trellis stack](https://roots.io/trellis/) which I guess is using PHP7, hence the error message. 

Any easy workarounds? I don't really want to start hacking the plugin code.

**Comment by johnclause** [comment] 2016-04-03 15:29
Duplicate of https://github.com/qTranslate-Team/qtranslate-x/issues/359

**Closed by johnclause** 2016-04-03 15:29 UTC

**Comment by growdigital** [comment] 2016-04-27 19:10
thanks for link, sorry not to reply sooner, didn't get notification!
