### ISSUE TITLE
Not Showing multi language switch Category in backend create product

### ISSUE THREAD

**Issue by gangasurendrareddy** [qTranslate-Team/qtranslate-x#273] opened 2015-09-28 11:40 UTC
Hi sir, 
Nice Plugin Working Fine.
Small Problem in my Website
 
Not Showing multi language switch Category in back end create product,  only show English version.
Product Name, Product Description working fine Both languages display.  only problem is product category display .

Please see Screen Shot.
![1](https://cloud.githubusercontent.com/assets/14871525/10134485/c7c479f0-65ee-11e5-87de-329c0baa34a4.jpg)    
![2](https://cloud.githubusercontent.com/assets/14871525/10134486/c7c854a8-65ee-11e5-8c2c-691a2a273769.jpg)

**Comment by johnclause** [comment] 2015-10-04 17:34
Those names are currently in admin language by design. I updated page https://qtranslatexteam.wordpress.com/desirable/. I am not sure when we would be able to get on it, but anyone is more than welcome to implement this change and to submit a pull request at [GitHub](https://github.com/qTranslate-Team/qtranslate-x/pulls).

I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.

**Closed by johnclause** 2015-10-04 17:34 UTC
Labels: enhancement
