### ISSUE TITLE
Tags and Categories not translated after migration

### ISSUE THREAD

**Issue by wocmultimedia** [qTranslate-Team/qtranslate-x#25] opened 2015-02-20 19:06 UTC
Hi,
 I wrote also in wp support. After migrating almost painless from mqTranslate I found out that Tags and Categories are not translated after the migration.
I have a bilingual site (English- Italian) and Italian tags/Categories are not present anymore. Clicking the language button only English version is available of both. Pages and Posts works correctly. If you visit http://www.norwayinteractive.biz/ changing language can see that About Us menu item changes because is a page title while other items not, they are tags and categories.
I wish you can find the fix because there's no error log in the php panel of server site
thanks
I tested with other themes too and tried to deactivate also some plugins but nothing changes and tags/categories are not available in Italian always English is shown.

**Comment by johnclause** [comment] 2015-02-20 21:35
Did you apply "import from mq"?

**Comment by wocmultimedia** [comment] 2015-02-20 22:20
I followed your step by step instructions including import from mq and I can also tell you that something is wrong in your explanation. After activating you have to first choose the language to be used then import from mq otherwise nothing happen and no settings or language will be imported. This is what I experienced. In fact, I had to manually select the language how where in mq then importing settings worked

**Comment by qtranslateteam** [comment] 2015-02-20 22:25
Those instructions were kindly written by one of the new users, I have to
check them. I wish you to get going asap meanwhile. Would you be able to do
database manipulation directly? You could copy then the option needed
manually from mq- to q-. I can lookup the exact name, if you have not done
so yet?

**Comment by wocmultimedia** [comment] 2015-02-20 22:34
I don't know how to do it, but if you tell me what I have to do I can enter MySql database and copy following your instruction. Have you seen that tags in both languages post are the same?

**Comment by johnclause** [comment] 2015-02-21 20:39
Yes, you got the options correctly. Just click on `option_value` of option `mqtranslate_term_name`, editor window will open, select all, copy to clipboard, then press `Esc` to cancel editing, then click below on the value of option `qtranslate_term_name`, editor opens, paste over the current value, press `Enter` or click outside of the editor to record your edits to the database. This should do it.

If clicking on field does not open the editor, then a click on yellow 'pen' on the left should open it.

However, I am really puzzled, why the import did not work for you. Before doing the above you may just try to import again from configuration page, there is a chance it will work this time.

There are other options also, which you would wish to preserve, but taxonomies names is the most important one. All others are easy to adjust again as wished on configuration page, but taxonomy names is the only one which requires a lot of manual work to re-enter.

**Comment by wocmultimedia** [comment] 2015-02-22 10:44
Well John,
if you visit the WP support you will see that in the step by step instructions I add this workaround and someone added that the import function is not working on the current version and that you got also a note from them to correct the problem. So it is not only my issue but currently plugin version doesn't work correctly. I tried several times to import from main plugin page before going to database of course

**Comment by johnclause** [comment] 2015-02-22 17:43
Yes, @wocmultimedia, I have finally reproduced the problem, indeed the import does not work. I am sorry about this. The fix is coming in 3.1 in the next couple days. Did you manage to get it working for you via direct database editing?

**Comment by wocmultimedia** [comment] 2015-02-22 17:50
yes John, I managed and shared my workaround in the wp support page of the plugin so other people solved the same problem and thanked me for sharing it. Thanks for your suggestion I succeeded also to support your great work.

**Comment by johnclause** [comment] 2015-02-22 17:50
Actually, if you are not done yet, you may try this temporary branch https://github.com/qTranslate-Team/qtranslate-x/archive/temporary.zip where import should work, but it is broken in other ways. You may only use it to do the import, and then switch back to 3.0 or to the latest beta https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip which seems to be ok so far but without import working. Sorry for the mess ... we will straighten this out as soon as possible.

**Comment by johnclause** [comment] 2015-02-22 17:52
Ok, great, thank you for supportive words.

**Comment by wocmultimedia** [comment] 2015-02-22 17:52
DOn't worry people understand what is happening and the hurry to make the plugin compatible...together we can win and go on. We show you the issue and then we try find a fix

**Comment by johnclause** [comment] 2015-02-22 23:19
@wocmultimedia, do you mind helping me to test 3.1-a1 https://github.com/qTranslate-Team/qtranslate-x/releases/tag/3.1-a1, which if everything is ok, will be relased as 3.1?
You may download it via link on that page, which is copied here too for the sake of convenience:
https://github.com/qTranslate-Team/qtranslate-x/archive/3.1-a1.zip

**Comment by wocmultimedia** [comment] 2015-02-23 08:55
Sorry, I'm not able to test a new version because I'm not a developer .

**Comment by johnclause** [comment] 2015-02-23 08:58
It is ok, we have released it already, now it is God's hands ;) I guess, we are done on this issue? Should we close it?

**Comment by wocmultimedia** [comment] 2015-02-23 09:05
with my workaround I succeeded to solve the problem I wish the new version will work with woocommerce 2.3.6 and qtranslate support for woocommerce plugins because I've a plenty of products in my other website. Thanks

**Comment by johnclause** [comment] 2015-02-23 09:10
We have just released plugin https://wordpress.org/plugins/woocommerce-qtranslate-x/ to integrate WooCommerce with qTranslate-X. Could you try it? It requires the latest WooCommerce, since WooCommerce folks kindly did some changes for us to make it work better.

**Comment by wocmultimedia** [comment] 2015-02-23 09:14
I will try it and let you know even I'm a bit afraid because I have about 200 products in my store.

**Comment by wocmultimedia** [comment] 2015-02-23 09:48
I used your latest version and works perfectly!!! I just activated your q-translated-x and it recognized all settings without having to make any other clicks.
I NEED your help for a simple thing, the flag in the widget are shown vertically and with bullet how can I set them horizontally without bullet? do I have to copy the css rules in my theme custom css? Please, visit http://www.wocmultimedia.biz/ and see my little issue. Thanks

Angelo

**Comment by wocmultimedia** [comment] 2015-02-23 12:59
Maybe there was a little conflict with the Virtue theme of kadencethemes but I solved it in some way adding some css rules copied from your widget to the theme options.

thanks
Angelo

**Comment by johnclause** [comment] 2015-02-23 18:16
Hi Angelo, yes, flags positions is fully customizable with CSS.

I am glad all seem to work for you. Yes, the author of 'qtranslate support for woocommerce', @mweimerskirch, has recently adjusted plugin to make it work with qTranslate-X too. However, that plugin was originally written for older q* versions and, as far as I know, it does not take advantage of the new integration features of -X, which particularly makes it possible to enable, for example, Language Switching Buttons in Woocommerce configuration pages.

That is why a new plugin with a completely different code was created. The new plugin will not work with older forks of qTranslate, as they do not have that new integration feature, which is designed with an idea in mind to make it possible to enable deep integration with a user inputted configuration in some text field of -X configuration. Such user modifiable text field is not yet implemented, and  WooCommerce & qTranslate-X plugin is a test tool  for us to tune this method.

You do not have to try it, since you are apparently ok with the way it is, but be aware of that opportunity in the future. It only works in full with the newest version of Woocommerce, 2.3.5, where they ask you to convert their database to their new format. That part has nothing to do with -X. With older version of WooCommerce some fields, especially in e-mail templates configuration pages, will not respond to Language Switching Buttons correctly. If you decide to try, surely make a backup copy first.

Best wishes,
John

**Comment by wocmultimedia** [comment] 2015-02-23 18:43
Hi John,
let me understand a little better because I'm just a video content producer and not a developer.
I have woocommerce 2.3.5 in my store and using qtranslate_support_for_woocommerce. It was useful to translate attributes because neither qtranslate nor mqtranslate were able to correctly create them.
If I install WooCommerce & qTranslate-X plugin what can happen? What's the difference with the one of @mweimerskirch? Is it possible you make a check with Michel and try to find a way to make the passage between the two plugin smoothly? That's would benefit you developers and us users to have a compatible website ready for the future. I understand your efforts but let's understand how always we are afraid of broken our sites especially for people like me that our work is different than creating great plugins or themes.
I'm sure you can do it because I'm a fan of qtranslate plugin and your work is very great.
Thanks 
Angelo

**Comment by johnclause** [comment] 2015-02-23 22:49
Hi Angelo, both plugins do not touch database and content, they simply present the content at front end translated and provide a way to enter multilingual content at back end. I think you can go back and forth between them without changing the content at all.

Yes, I understand your concerns, and you really do not have to do anything, I just thought it could be fun, but I am sure you have a lot of other more important things to spend time on. The rule of thumb: 'do not touch what already works fine' ;)

Best wishes,
John

P.S. I think we can close this issue now. Reopen if you have more to discuss.

**Closed by johnclause** 2015-02-23 22:49 UTC

**Comment by wocmultimedia** [comment] 2015-02-24 09:55
Hi John,
I have a simple question and i wish do not disturb you but it's a question to better use the plugin. When I create a new tag or category with your plugin I have two different panels, one for each language. The question is do the slug be the same in both languages? I try to be more clear. If I create in English a category called SHOP slug "shop" that in Italian become NEGOZIO the slug in Italian panel must be "shop" or can be different?
Thanks
Angelo

**Comment by johnclause** [comment] 2015-02-24 10:07
Slug is language-neutral, the same for all languages, unless you also use "Qtranslate Slug" plugin.

**Comment by wocmultimedia** [comment] 2015-02-24 10:28
Thanks a lot!!! You confirmed my tests and suppositions in fact I don't use "Qtranslate Slug" it made problem in the past so I avoid of using more than needed plugins.
I tried to install woocommerce-qtranslate-x-master-master.zip but it failed what's wrong with my installation? maybe do I have to download from another place?

**Comment by wocmultimedia** [comment] 2015-02-24 10:38
I downloaded woocommerce-qtranslate-x1.0 and installed correctly. It works in general fine but I get this result in the cart display 
![errordisplayingattribute](https://cloud.githubusercontent.com/assets/2352240/6347608/92068f58-bc19-11e4-8fed-66eb5414ee8e.jpg)

**Comment by johnclause** [comment] 2015-02-25 01:32
Thanks you, Angelo, this is really helpful. At which page those fields are entered at the back end? Michel (@mweimerskirch), does it look familiar to you? Which filter do we need to add?

**Comment by wocmultimedia** [comment] 2015-02-25 09:49
hi sorry for the delay but I was out of town. here's a shot of backend maybe it can be useful better than my words 
![backendpage](https://cloud.githubusercontent.com/assets/2352240/6368301/aa7c83ea-bcdb-11e4-946c-4b89b8a29449.jpg) 
Let me know if I can help you in some way, I'm ready to supply you the information you need according with my little knowledges but I don't understand the filter question.

**Comment by wocmultimedia** [comment] 2015-02-28 13:22
Hello John,
Here's a deep test about. You can understand from the shot enclosed The former attribute created with qTranslate-support for woocommerce in frontend are still not shown correctly sing latest version of qx and woocommerc-qx plugin. (see the Format in the shot) While, if I create a new attribute item it's correctly shown (see Lingua - Tedesco). I wish it can help you understand the problem
![frontendvisualizationproblem](https://cloud.githubusercontent.com/assets/2352240/6426327/2cc1eb8a-bf55-11e4-8acc-55d9c08a6b3d.jpg)

**Comment by johnclause** [comment] 2015-03-05 06:37
Hi Angelo, sorry for the delay in response. Unfortunately, I cannot reproduce what you show me, because I do not have any site with sophisticated enough Woocommerce configuration like yours. Can you advise me how to mimic what you have? Which free public theme supports Woocommerce well enough, so that I could try similar configuration like yours?

**Comment by wocmultimedia** [comment] 2015-03-05 09:30
Hello John,
if you give me an email I will send you the theme I'm using so you can make a better check. Eventually, here's a free version of the theme I'm using https://wordpress.org/themes/virtue/
My configuration isn't very sophisticated but just use two languages and I remember was exactly my website that (@mweimerskirch) used to develop his plugin. I think Michael could help you understand what filter use for the items because following my feedback he solved the problem in just a couple of hours at the time. 
Of course there's a work around of rewriting the items using your plugin switch but maybe it could be avoid of.
Thanks, for your patience and the support
Angelo

**Comment by johnclause** [comment] 2015-03-05 10:07
Hi Angelo, email is published in plugin source, it is gtranslateteam a t g m ail d co m. I downloaded Virtue and will try to mimic your setup, in a couple of days. Small world ... Michel already gave me his solution, but I would like to find out why exactly it does not work, since, at first glance, what he gave me is redundant. I am sure he could figure it out too, but everyone has  priorities to maintain, he is busy with other stuff too. It would actually help me if you could setup a test-copy of your site, where I could login and mess around. Use that email to send me login if you can find time for that. Thanks a lot, John

**Comment by wocmultimedia** [comment] 2015-03-06 12:10
Thanks a lot John! You solved the problem and gave me the chance to not use many different plugins.
