### ISSUE TITLE
strange URL when I click switch Language 

### ISSUE THREAD

**Issue by WillyBrownHair** [qTranslate-Team/qtranslate-x#182] opened 2015-06-12 11:43 UTC
I have an Ajax manu with a switch language button.
After I click a menu item, the nav is replace by a data nav. But my issue is about the new link of the switch language button.

The link before click switch langage button : 
http://my-site.com/contact/

the link after :
http://my-site.com/en/contact/?_=1434107365014

I would like : 
http://my-site.com/en/contact/

The problem doesn't exist if i reload my page and I click directly on switch language button. I have this issue when I reload my page -> click another link menu -> click my switch language button. Problem seem to be AFTER ajax call.

Thanks for you help
Willy

**Comment by johnclause** [comment] 2015-06-12 15:26
It is probably on your theme or plugin. For me to reproduce, I need a lot more information. Do those link actually work correctly?

**Comment by WillyBrownHair** [comment] 2015-06-13 07:27
the real link of the project is http://sylvain-bouzat-photographe-mariage.com
Thanks.

**Comment by johnclause** [comment] 2015-06-13 22:05
Hi @WillyBrownHair: at least, it seems to work, that query string '?_=1434232293567' is apparently ignored on all pages. Do you have any idea where the string '?_=1434232293567' may be coming from? Does it ring any bells for you? Is your theme doing something funny? Actually it looks like a timestamp?

I would not know where it comes from without a deeper investigation. Do you have any error messages in the log or somewhere by any chance? Did you try to do initial troubleshooting steps: https://qtranslatexteam.wordpress.com/troubleshooting/? I doubt it will help though in this case. You need to go through the PHP code and figure out where that query comes from. Once it is known, then you may think what to do about it.

**Comment by WillyBrownHair** [comment] 2015-06-14 11:18
actually the string at the end of the URL isn't each time the same. It change every time. 
I developed personally this theme and there nothing strange in php or js file... 
I continue my research.
Thanks

**Comment by johnclause** [comment] 2015-06-14 14:17
I think that string is a time stamp, it matches linux time in ms http://www.epochconverter.com/ Maybe some plugin does some kind of usage tracking?

**Comment by WillyBrownHair** [comment] 2015-06-15 06:34
I found what was wrong.
In my ajax reponse, the parameter 'cache' was 'false' . He must be 'true'.
Timestamp in URL has disappeared :)
http://stackoverflow.com/questions/5022557/jquery-version-1-5-ajax-script-tag-timestamp-problem

Thanks again for your help !

**Comment by johnclause** [comment] 2015-06-15 14:13
Wow, I am glad you figured it out. I am closing this issue, we can still write into a closed issue, or we can re-open it, if needed.

**Closed by johnclause** 2015-06-15 14:13 UTC
Labels: question
